// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzA4egVa9m7WLh1mRECFwM361GOxF1DU',
    appId: '1:716883137655:web:8dba3c6e6e58fb7a00a272',
    messagingSenderId: '716883137655',
    projectId: 'attendo-sih',
    authDomain: 'attendo-sih.firebaseapp.com',
    storageBucket: 'attendo-sih.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZbwQNv15iC5RhU8Xhk7fil6SmYF-T-Is',
    appId: '1:716883137655:android:2b109e5780c46cc500a272',
    messagingSenderId: '716883137655',
    projectId: 'attendo-sih',
    storageBucket: 'attendo-sih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GZpF3zchBOBjbOZD5cMqDiaWTC5gTNw',
    appId: '1:716883137655:ios:963f1c99f2ffef3e00a272',
    messagingSenderId: '716883137655',
    projectId: 'attendo-sih',
    storageBucket: 'attendo-sih.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9GZpF3zchBOBjbOZD5cMqDiaWTC5gTNw',
    appId: '1:716883137655:ios:963f1c99f2ffef3e00a272',
    messagingSenderId: '716883137655',
    projectId: 'attendo-sih',
    storageBucket: 'attendo-sih.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKzA4egVa9m7WLh1mRECFwM361GOxF1DU',
    appId: '1:716883137655:web:9c140918a4aad57a00a272',
    messagingSenderId: '716883137655',
    projectId: 'attendo-sih',
    authDomain: 'attendo-sih.firebaseapp.com',
    storageBucket: 'attendo-sih.firebasestorage.app',
  );
}
